name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        DKTAG=guillaumeai/server:hfjudkbase
        DATE_STAMPED_TAG=guillaumeai/server:hfjudkbase-$(date +%y%M%d)
        echo "$DATE_STAMPED_TAG" >> $GITHUB_ENV
        docker build . --file Dockerfile --tag $DATE_STAMPED_TAG
        echo "DKTAG=guillaumeai/server:hfjudkbase" >> $GITHUB_ENV
    - name: Log in to DockerHub
      uses: docker/login-action@v1
      with:
        username: "jgwill"
        password: ${{ secrets.DK_TOKEN }}
    - name: Tag the Docker image with the common name
      run: docker tag ${{ env.DATE_STAMPED_TAG }} ${{ env.DKTAG }}
    - name: Push the Docker image with the date-stamped tag
      run: docker push ${{ env.DATE_STAMPED_TAG }}
    - name: Push the Docker image with the common name tag
      run: docker push ${{ env.DKTAG }}